apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveller-service-app
  labels:
    app: traveller-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traveller-service-app
  template:
    metadata:
      labels:
        app: traveller-service-app
    spec:
      containers:
        - name: traveller-service-app
          image: dailycodebuffer/department-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: traveller-service-svc
spec:
  ports:
    - targetPort: 8084
      port: 80
  selector:
    app: traveller-service-app
